source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_dependencies', '~> 2.13'
gem 'rake_terraform', '~> 1.21'
gem 'rake_circle_ci', '~> 0.9'
gem 'rake_github', '~> 0.7'
gem 'rake_ssh', '~> 0.6'
gem 'rake_gpg', '~> 0.14'
gem 'confidante', '~> 0.27'
gem 'rspec', '~> 3.11'
gem 'awspec', '~> 1.25'
gem 'git', '~> 1.10'
gem 'semantic', '~> 1.6'
gem "rubyzip", ">= 1.3.0"
